from pathlib import Path
import json,time,subprocess,hashlib,rospy
from std_msgs.msg import String,Bool
r=Path('/root/tcei_competition_20260919');rel=r/'releases/dev_v7_t1_07';base=Path('/root/gpufree-data/tcei_competition_20260919');run=base/'single07_torch01';stack=base/'no_action07_01';rospy.init_node('tcei_single07_supervisor',anonymous=True);assert json.loads((r/'t1_clear07_01_grade.txt').read_text())['passed']==7;assert (run/'rgbd/reference.npz').exists() and (run/'scalars/ready.json').exists();assert not (run/'episode').exists();assert all(rospy.get_param(k) is False for k in ('/tcei_controller/execute','/tcei_nine/execute'));assert json.loads((stack/'read_only_ready.json').read_text())['grasp_capability'] is True
manifest=json.loads((rel/'tcei_stack/BUILD_MANIFEST.json').read_text());assert all(hashlib.sha256((rel/'tcei_stack'/n).read_bytes()).hexdigest()==h for n,h in manifest['files'].items());guard=['/usr/bin/python3',str(rel/'harness/process_guard.py')]
for name in ('nine','controller','perception','sim'):subprocess.run(guard+['check',str(stack/'pids'/(name+'.json'))],check=True)
for name in ('rgbd','scalars'):subprocess.run(guard+['check',str(run/'pids'/(name+'.json'))],check=True)
scene=json.loads(rospy.wait_for_message('/tcei/candidates',String,timeout=5).data);torches=[c for c in scene['candidates'] if c['class']=='Torch'];assert len(torches)==1 and torches[0]['identity_status']=='confirmed' and scene['scene_complete'];assert rospy.wait_for_message('/Jaka/gripper_is_captured',Bool,timeout=5).data is False;gold={'registered_at':time.time(),'instruction':'把一个军用手电筒放到左侧传送带','expected_stable_id':torches[0]['stable_id'],'expected_source_pixel':torches[0]['pixel'],'expected_class':'Torch','expected_side':'left','annotation':'Same unique Torch independently viewed before model calls; exact source scene retained.','scope':'engineering single-object, not one of 30 rounds'};(run/'expected_target.json').open('x').write(json.dumps(gold,ensure_ascii=False,indent=2));(run/'before_scene.json').open('x').write(json.dumps(scene,ensure_ascii=False,indent=2));(stack/'round_started.lock').open('x').write(json.dumps({'engineering_only':True,'run':str(run),'started_at':time.time()}));cmd=['/usr/bin/python3','-u',str(rel/'tcei_stack/run_episode.py'),'--instruction',gold['instruction'],'--task-source','engineering_single','--budget','180','--output',str(run/'episode')];(run/'dispatch.json').open('x').write(json.dumps({'command':cmd,'dispatch_at':time.time(),'model_and_controller_source':str(rel),'budget':180,'competition_round':False},ensure_ascii=False,indent=2))
try:
 rospy.set_param('/tcei_controller/execute',True);rospy.set_param('/tcei_nine/execute',True)
 with (run/'logs/episode.log').open('x') as log:
  child=subprocess.Popen(cmd,stdout=log,stderr=subprocess.STDOUT);(run/'episode_process.json').write_text(json.dumps({'pid':child.pid,'started_at':time.time()}));code=child.wait()
finally:
 rospy.set_param('/tcei_nine/execute',False);rospy.set_param('/tcei_controller/execute',False)
(run/'supervisor_finished.json').write_text(json.dumps({'returncode':code,'finished_at':time.time(),'execution_disabled':True}));print('SINGLE07_EPISODE_FINISHED',code,flush=True)
